version: "3"
services:
  hub:
    image: selenium/hub:3.141
    ports:
      - "4444:4444"
  chrome:
    image: selenium/node-chrome:3.141
    depends_on:
      - "hub"
    environment:
      - HUB_HOST=hub
  ff:
    image: selenium/node-firefox:3.141
    shm_size: '1gb'
    depends_on:
      - "hub"
    environment:
      - HUB_HOST=hub
  search-module-ff:
    image: nitinmanojkumar/selenium-docker
    depends_on:
      - chrome
      - ff
    environment:
      - BROWSER=firefox
      - HUB_HOST=hub
      - MODULE=search-module.xml
    volumes:
      - ./output-from-container-firefox:/usr/share/udemy/test-output
  search-module-chrome:
    image: nitinmanojkumar/selenium-docker
    depends_on:
      - chrome
      - ff
    environment:
      - BROWSER=chrome
      - HUB_HOST=hub
      - MODULE=search-module.xml
    volumes:
      - ./output-from-container-chrome:/usr/share/udemy/test-output
# version: "3"
# services:
#   hub:
#     image: dosel/zalenium
#     logging:
#       driver: "none"
#     ports:
#       - "4444:4444"
#       - "5555:5555"
#     volumes:
#       - /var/run/docker.sock:/var/run/docker.sock
#       - /usr/bin/docker:/usr/bin/docker
#     command: >
#       start --desiredContainers 2 
#             --maxDockerSeleniumContainers 2 
#             --maxTestSessions 3 
#             --videoRecordingEnabled false